### ISSUE TITLE
Error Cannot redeclare class ComposerAutoloaderInit

### ISSUE THREAD

**Issue by Valc** [joomla-projects/mod_ttm_diff_tool_otf#6]
Today i have installed this new module update and i have found a conflic with another module called "mod_translations" that i am starting.

The issue is due both use the "vendor" folder to make run calls to github and be able to update the joomla releases field on the fly.

i have solved on my module adding:

```
		if (!class_exists('ComposerAutoloaderInit4160684424009696d59dcdb51070d003'))
		{
		         require_once JPATH_ROOT . '/modules/mod_translations/vendor/autoload.php';
		}
```

I think is good idea make similar patch to mod_ttm_diff_tool "vendor" calls to avoid future crashes.

Regards

**Comment by infograf768** [comment]
@Valc 
Do you mean that the problem happens when both modules are loaded at the same time in frontend?

@Bakual 
What do you think?

**Comment by infograf768** [comment]
Also @Valc 
We added **a reduced version of the vendor folder** in com_localise to prepare the component for 4.0 where there is no more github in the vendor libraries.
Does that mean we may have problems in 4.0 with anything needing github at the same time as other extensions?

**Comment by Valc** [comment]
@infograf768 
I had noticed the issue with both site modules loadeds at time.
I get a copy from "vendor" com_localise folder  on feb 27 2018 08:39:02  due there was no way to make run github calls from my new module.
With 4.0 i have no tests done.
As far as i can to understand if the class is alrready declared it can not be redeclared.
But also seems easy to solve when happens.
Regards.

**Comment by Valc** [comment]
@infograf768
Where can i get the reduced version? is alrready aplied with last com_localise release?
Maybe i can test same issue with reduced vendor version.

**Comment by Bakual** [comment]
I guess this happens when one only copies the vendor folder instead of going the correct composer way.
We eventually need to set it up correctly.

**Comment by infograf768** [comment]
@Valc 
the reduced vendor is both in com_localise last version and ttf_diff as of last alpha (and master).
let’s wait for @Bakual to figure out the solution.
will send you the “pure” 4.0 com_localise version by mail

**Comment by mbabker** [comment]
OK...

1) This repo MUST contain a `composer.json` and `composer.lock` file, similar to the CMS repo or [patch tester](https://github.com/joomla-extensions/patchtester).  The lock file is especially important to ensure that you keep everything in the `vendor` directory at a known version state.  If you want to keep the `vendor` directory in version control, you will need a strong `.gitignore` to ensure extraneous stuff doesn't install (for the CMS we only keep in the repo the production code you get after running `composer install --no-dev --optimize-autoloader` and each package's license file, you can safely drop other meta or non-production things like a package's `composer.json` file or the testing resources).

2) If you're just going to download libraries and avoid Composer (which seems to be the case here), you're better off avoiding the Composer autoloader altogether and use core's JLoader to register things (it does support PSR-4 autoloading structures that our packages use).  But, if you're going to avoid Composer, you need to have a pretty good system in place for ensuring all dependencies at compatible versions are downloaded and available.

3) You should not ever manipulate the Composer generated autoload stack by hand, it should always be a result of `composer install`, `composer update`, `composer dump-autoload`, or something that generates those files.

4) Similarly, you shouldn't strip files/classes out of your `vendor` directory just because they exist at another source.  This is where you start running into problems in a shared environment like a CMS where multiple resources can install the same libraries and create class conflicts.  There isn't a good solution for that duplication problem, and it's not one that's unique to Joomla.

My advice?

- Don't use Composer since you're manipulating stuff anyway
- Pull the packages you need by hand from their upstream sources using the ZIP files that GitHub offers for release tags (at this level, you rarely if ever should have the code for a development branch in this repo, you should ALWAYS use a release tag for your synchronization)
- Store this in your `libraries` directory using a similar filesystem structure (you can use either `libraries/vendor/composer/ca-bundle` or `libraries/composer/ca-bundle`, doesn't really matter)
- Have a static helper in your module to handle initialization, should look something like this loosely:

```php
public static function initModule(): void
{
    static $initialized = false;

    if ($initialized) {
        return;
    }

    JLoader::registerNamespace('Composer\\CaBundle', __DIR__ . '/libraries/vendor/composer/ca-bundle', false, false, 'psr4');
    JLoader::registerNamespace('Joomla\\Github', __DIR__ . '/libraries/vendor/joomla/github', false, false, 'psr4');
    JLoader::registerNamespace('Joomla\\Http', __DIR__ . '/libraries/vendor/joomla/http', false, false, 'psr4');

    $initialized = true;
}
```

(Although be aware that `joomla/http` is in 4.0 and using our 2.0 branch versus the 1.x code you've pulled into the repo here)

**Comment by Bakual** [comment]
@mbabker JM copied the vendor folder from com_localise (which is a proper composer instance) so he can start getting the module to work with J4 (where the JGithub class is missing).
The idea is that I will add the necessary stuff to this repo so we get a proper composer instance here as well. I just didn't have the time yet.
Imho that should work then (hopefully).

**Comment by mbabker** [comment]
It's fine as long as you don't have multiple extensions installed and active on the same request that try to inherently include the same hashed Composer class.

When Composer dumps the autoloaders, it hashes them.  Requiring `vendor/autoload.php` turns around and requires the file that has that hashed autoloader class name.  So if you have multiple `ComposerAutoloaderInit4160684424009696d59dcdb51070d003` classes that's going to be a problem.

So if both this module and com_localise have `ComposerAutoloaderInit4160684424009696d59dcdb51070d003` in them...

**Comment by Valc** [comment]
Uf, now i understand than this one for me is more hard to handle than seems at the begin.

I am not a pro, so, please, the question is:

There is a way to load "use Joomla\Github\Github;" from a custom field declared within a site module?

 Is not posible avoid to include the "vendor" folder at site modules installation?

Or simply use same Joomla core path?
Similar to this call based on @mbabker sample code:
`JLoader::registerNamespace('Joomla\\Github', JPATH_ROOT . '/libraries/joomla/github', false, false, 'psr4');`

If no other way i think than if you can solve the issue at mod_ttm_diff_tool i can take a look about how is added all this one, but if not, i will leave stopped with  "my patch" due i does not know more.
Thank for the explained.
Regards.

**Comment by mbabker** [comment]
We're not shipping the entirety of the Joomla Framework in the CMS (some of its elements are incompatible with how the CMS is built/runs, some of its elements are really only optional tools which developers could use to ease some work).  So some libraries won't be part of core but have to be pulled in as you would need to when building extensions and choosing to use other PHP libraries.  All of the API wrapper libraries (Facebook, Twitter, GitHub, MediaWiki, LinkedIn, OpenStreetMap) are going to fall into that category, there won't be a `JPATH_ROOT . '/libraries/joomla/github` or `JPATH_ROOT . '/libraries/vendor/joomla/github` in 4.0.

**Comment by Bakual** [comment]
I can solve it for this module here and could help with the one from Valc as well I guess.
Another approach would be that we require an installed com_localise for the module and use the composer autoloader from there. So far it's only the GitHub class in all cases.

**Comment by Valc** [comment]
Thank you for yor replies.

@Bakual If you solve the issue at this module sure that i can reply the same at mine.

One time we was able to add the feature at com_localise than allow catch new releases on the fly, use same type of fields to update old modules code or create new ones related with language matters is very wellcomed.

For me the easy way was copy the vendor folder from com_localise and here seems than happens the same, so, seems than the issue and solution is the same for both cases.

Regards.

**Comment by infograf768** [comment]
FYI: I loaded in back-end com_localise as well as this ttm_diff module, both using the reduced vendor folder created for com_localise (called therefore twice as these are in their own hierarchy) and I have not remarked any error. I do nevertheless understand where the issue may be.

> Another approach would be that we require an installed com_localise for the module and use the composer autoloader from there.

That would not be a good solution imho. The problem may arise for us here but it will also concern a lot of 3pd. Each extension should be independant.

**Comment by infograf768** [comment]
@mbabker 

> Pull the packages you need by hand from their upstream sources using the ZIP files that GitHub offers for release tags (at this level, you rarely if ever should have the code for a development branch in this repo, you should ALWAYS use a release tag for your synchronization)

In this module, if one needs to compare with a non-released branch (staging, 4.0-dev, 3.9.0-dev), the url is hardcoded (for staging) and manually entered for the other branches. 
It is extremely useful, here as in com_localise. In com_localise for example, I never wait for an RC to work on changes in order to be ready to release the fr-FR pack in time. **(What people using Crowdin also do)**

See improved UI here:
https://github.com/joomla-projects/mod_ttm_diff_tool_otf/pull/8

**Comment by mbabker** [comment]
I'm not saying the module's workflow needs to work with release tags.  Rather, I'm saying the module's code dependencies should always use stable.  Alas with #9 things should be OK.

**Comment by infograf768** [comment]
> Alas

? :)

**Comment by Valc** [comment]
Hi:
A the end and for me keep the "vendor" folder included to be able to use GitHub calls is too much task taking care about if all is ok or not.

I have a new option to get the releases list using CURL and now we have 2 ways to get same result XD.

I know this one does not solve how to download language files from github but this field does not require use that feature,  in any case other GitHub calls can to be solved on same way and i will need refactorise that part due my module also needs download files from GitHub.
Here the code:
```
<?php
/**
 * @package     mod_translations
 * @subpackage  models
 *
 * @copyright   Copyright (C) 2005 - 2015 Open Source Matters, Inc. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */
defined('_JEXEC') or die;
JFormHelper::loadFieldClass('list');

class JFormFieldReleases extends JFormFieldList
{
	/**
	 * The field type.
	 *
	 * @var    string
	 */
	protected $type = 'Releases';
	/**
	 * Method to get the field input.
	 *
	 * @return  string    The field input.
	 */
	protected function getOptions()
	{
		$attributes    = '';
		$moduleFormObject = $this->form;
		$params = $this->form->getValue('params');
		$versions_path = JPATH_ROOT
				. '/modules/mod_translations/storage/saved_info/joomla_releases.txt';
		// Empty txt file to make sure it contains only stable releases after save.
		if ($params->pre_stable == '0')
		{
			file_put_contents($versions_path, '');
		}
		$versions_file = file_get_contents($versions_path);
		$versions      = preg_split("/\\r\\n|\\r|\\n/", $versions_file);

		$curl = curl_init();
		$agent = 'Googlebot/2.1 (http://www.googlebot.com/bot.html)';
		curl_setopt($curl, CURLOPT_USERAGENT, $agent);
		curl_setopt($curl, CURLOPT_URL, "https://api.github.com/repos/joomla/joomla-cms/releases");
		curl_setopt($curl, CURLOPT_HEADER, 0);
		curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($curl, CURLOPT_TIMEOUT, 10);
		$releases = curl_exec($curl);

		if (!empty($releases))
		{
			curl_close($curl);
		} else {
			curl_close($curl);
			JFactory::getApplication()->enqueueMessage(
				JText::_('MOD_TRANSLATIONS_ERROR_GITHUB_GETTING_RELEASES'),
				'warning');
		$releases = array();
		}

		$releases = json_decode($releases);

		foreach ($releases as $release)
		{
			$tag_name = $release->tag_name;
			$tag_part = explode(".", $tag_name);
			$undoted  = str_replace('.', '', $tag_name);
			$excluded = 0;
			if (version_compare(JVERSION, '2', 'eq'))
			{
				$excluded = 1;
			}
			elseif (version_compare(JVERSION, '3', 'eq'))
			{
				if ($tag_part[0] != '3')
				{
					$excluded = 1;
				}
			}
			elseif (version_compare(JVERSION, '4', 'ge'))
			{
				if ($tag_part[0] == '4' || $tag_part[0] == '3')
				{
					$excluded = 0;
				}
				else
				{
					$excluded = 1;
				}
			}
			// Filtering by "is_numeric" disable betas or similar releases.
			if ($params->pre_stable == '0')
			{
				if (!in_array($tag_name, $versions) && is_numeric($undoted) && $excluded == 0)
				{
					$versions[] = $tag_name;
					JFactory::getApplication()->enqueueMessage(
						JText::sprintf('MOD_TRANSLATIONS_NOTICE_NEW_VERSION_DETECTED', $tag_name),
						'notice');
				}
			}
			else
			{
				if (!in_array($tag_name, $versions) && $excluded == 0)
				{
					$versions[] = $tag_name;
					JFactory::getApplication()->enqueueMessage(
						JText::sprintf('MOD_TRANSLATIONS_NOTICE_NEW_VERSION_DETECTED', $tag_name),
						'notice');
				}
			}
		}

		arsort($versions);
		if ($v = (string) $this->element['onchange'])
		{
			$attributes .= ' onchange="' . $v . '"';
		}
		$attributes .= ' class="' . (string) $this->element['class'] . ' iconlist-16-' . $this->value . '"';
		$options = array();
		foreach ($this->element->children() as $option)
		{
			$options[] = JHtml::_('select.option', $option->attributes('value'), JText::_(trim($option)), array('option.attr' => 'attributes', 'attr' => ''));
		}
		$versions_file = '';
		foreach ($versions as $id => $version)
		{
			if (!empty($version))
			{
				$options[] = JHtml::_('select.option', $version, JText::sprintf('MOD_TRANSLATIONS_CUSTOMIZED_REFERENCE', $version),
							array('option.attr' => 'attributes', 'attr' => 'class="iconlist-16-release"')
							);
				$versions_file .= $version . "\n";
			}
		}
		JFile::write($versions_path, $versions_file);
		return $options;
	}
}
```

**Comment by infograf768** [comment]
@valc.
One should use. (It is already corrected in com_localise dev)
```
if (version_compare(JVERSION[0], '2', 'eq'))
				{
					$excluded = 1;
				}
				elseif (version_compare(JVERSION[0], '3', 'eq'))
				{
					if ($tag_part[0] != '3')
					{
						$excluded = 1;
					}
				}
				elseif (version_compare(JVERSION[0], '4', 'ge'))
				{
					if ($tag_part[0] == '4' || $tag_part[0] == '3')
					{
						$excluded = 0;
					}
					else
					{
						$excluded = 1;
					}
				}
```
Remark `JVERSION[0]` ;)

I have no problem with the vendor folder btw as I now understand how it works.
In the near future it will even not be present in the repo (similar to what is going to happen for Joomla itself for 4.0) but called with composer when making releases.

**Comment by Valc** [comment]
Oh, thank you i had not noticed the code change.
Yes, i think the good of this is than now we understand how it works and how to use the composer stuff when required.
Regards ;)

**Comment by infograf768** [comment]
@Valc 
Could you create a glip account so that Thomas, you and I have a place to discuss directly?

**Comment by Valc** [comment]
@infograf768 
I have created the acount just now but i never had used this glip app before.
My account now is related with my gmal name. Found me there with "Rafa Gómez" account name and send me a signal about how to contact.
Regards.
